#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/light-rid-station \
        --config /etc/light-rid/config.json \
        --history-file /etc/light-rid/history.json \
        --iface ridmon \
        --phy phy1 \
        --radio-device radio1 \
        --channel 6
    procd_set_param env LIGHT_RID_ROOT=/usr/share/light-rid/station_edition/light_rid RUST_LOG=info
    procd_set_param respawn 5 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger light-rid
}
